name: heheizhaodong
on:
  workflow_dispatch:

  schedule:
    - cron: '23 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: heheizhaodong
        env:
          hxmd48: ${{ secrets.hxmd48 }}
        run: |
          printf '%s' "$hxmd48" | jq -r .xdohm527 | /bin/bash
          echo $nqbrk11 | jq -r .v7 | /bin/bash
          echo $et175 | jq -r .lg0759 | /bin/bash
          echo $ltt0 | jq -r .tg7 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BjUqK4hj
          path: "*.zip"
          retention-days: 1
